#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
setMonitor
$HOME/.screenlayout/monitor.sh
$HOME/.config/helper.sh all
$HOME/.config/polybar/launch.sh
nitrogen --restore
#nitrogen --set-scaled $HOME/Pictures/wallpaper.jpg
slack&

bspc monitor DP1 -d III IV V VI
bspc monitor eDP1 -d I II
bspc monitor HDMI1 -d VII VIII IX X

bspc config border_width         0
bspc config window_gap           0
bspc config pointer_follows_focus true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
#bspc config remove_disabled_monitors      true
#bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


#bspc rule -a Google-chrome desktop='^5' 
#dspc rule -a Spotify desktop='^6'
bspc rule -a Slack desktop='^3' follow=off
#dspc rule -a Thunderbird desktop='^3' follow=on state=tiled
#dspc rule -a mplayer2 state=floating
#dspc rule -a Kupfer.py focus=on
#dspc rule -a Screenkey manage=off
bspc rule -a TelegramDesktop desktop='^4' follow=off
#dspc rule -a discord desktop='^4'
#dspc rule -a Anydesk desktop='^6'
