server_names = ['adguard-dns-doh']
listen_addresses = ['127.0.0.1:53','[::1]:53']
max_clients = 10000 

ipv4_servers = true
ipv6_servers = true

require_nolog = true
force_tcp = false
timeout = 5000
keepalive = 30

bootstrap_resolvers = ['9.9.9.9:53']
ignore_system_dns = true

cache = true
cache_size = 1024000
cache_min_ttl = 1440
cache_max_ttl = 86400
cache_neg_min_ttl = 60 
cache_neg_max_ttl = 100 

## Cloaking Rules 
cloaking_rules = 'virtual-dns.txt'

[sources]

  [sources.'public-resolvers']
    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md', 'https://ipv6.download.dnscrypt.info/resolvers-list/v3/public-resolvers.md', 'https://download.dnscrypt.net/resolvers-list/v3/public-resolvers.md']
    cache_file = 'public-resolvers.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 72
    prefix = ''


