#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
$HOME/.config/helper.sh all
#$HOME/.screenlayout/home.sh
$HOME/.config/polybar/launch.sh
nitrogen --restore

monitor=$(xrandr | grep -w -c connected)
if [ monitor == 1 ]; then 
	bspc monitor eDP-1 -d I II III IV V VI VII VIII
else
	bspc monitor eDP-1 -d I II III IV
	bspc monitor DP-1 -d V VI VII VIII
	bspc monitor DP-1 -s eDP-1
fi

bspc config border_width         0
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
#bspc config remove_disabled_monitors      true
#bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^6' state=tiled follow=on
bspc rule -a Google-chrome desktop='^6' state=tiled
bspc rule -a Spotify desktop='^7'
bspc rule -a Slack desktop='^3' follow=on state=tiled
bspc rule -a Thunderbird desktop='^2' follow=on state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a TelegramDesktop desktop='^4' follow=on
bspc rule -a discord desktop='^4'
bspc rule -a Anydesk desktop='^5'
